---
baseURL: https://louislefebvre.net/
copyright: "2025 Louis LeFebvre"
enableRobotsTXT: true
languageCode: en-us
sectionPagesMenu: main
theme: bearcub
title: Louis LeFebvre (✿◠‿◠)
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - name: "PGP"
    url: "/public-key.txt"
    weight: 10
  - name: "lsh"
    url: "/construction.html"
    weight: 80
