---
baseURL: https://louislefebvre.net/
copyright: "© 2026 Louis LeFebvre"
enableRobotsTXT: true
languageCode: en-us
sectionPagesMenu: main
theme: hugo-bearcub
title: Louis LeFebvre (✿◠‿◠)
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
  - name: "PGP"
    url: "/public-key.txt"
    weight: 10
